### ISSUE TITLE
Subject 'some-topic-value' not found.; error code: 40401*

### ISSUE THREAD

**Issue by xmlking** [thake/avro4k-kafka-serializer#12]
it was automatically  creating   schema in **schema registry** with release 0.13.0 version
but I am getting error while testing with **latest code** + **dependencies**. after schema is added then no error. 
is it expected behaviour ? 

Should  I first add schema to **schema registry** before using this serializer? 

**RestClientException: Subject 'all-in-topic-value' not found.; error code: 40401**

```log
com.github.thake.kafka.avro4k.serializer.AbstractKafkaAvro4kSerDe: Caught exception while trying to talk to the schema registry. Retry attempt 0
io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject 'all-in-topic-value' not found.; error code: 40401
        at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:292)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:352)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:437)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:424)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getIdFromRegistry(CachedSchemaRegistryClient.java:236)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getId(CachedSchemaRegistryClient.java:382)
        at com.github.thake.kafka.avro4k.serializer.AbstractKafkaAvro4kSerDe$getSchemaIdWithRetry$2.invoke(AbstractKafkaAvro4kSerDe.kt:83)
        at com.github.thake.kafka.avro4k.serializer.AbstractKafkaAvro4kSerDe$getSchemaIdWithRetry$2.invoke(AbstractKafkaAvro4kSerDe.kt:24)
        at com.github.thake.kafka.avro4k.serializer.AbstractKafkaAvro4kSerDe$doCallToSchemaRegistry$2$1.invokeSuspend(AbstractKafkaAvro4kSerDe.kt:67)
        at com.github.thake.kafka.avro4k.serializer.AbstractKafkaAvro4kSerDe$doCallToSchemaRegistry$2$1.invoke(AbstractKafkaAvro4kSerDe.kt)
        at com.github.michaelbull.retry.RetryKt$retry$5.invokeSuspend(Retry.kt:52)
        at com.github.michaelbull.retry.RetryKt$retry$5.invoke(Retry.kt)
```

**Comment by xmlking** [comment]
@thake Thank you for contributing this great module.   I extended your code to add encrypt/decrypt layer. 

First I tried to extend your `AbstractKafkaAvro4kSerDeConfig` , `Avro4kSerde` `AbstractKafkaAvro4kDeserializer` and `AbstractKafkaAvro4kSerializer` classes, but faced above issue. This is caused because you have references to `AbstractKafkaAvro4kSerDeConfig` constants  deep in other classes.

I ended up copying  more classes to isolate dependencies. 
**Wonder if you can take a look and find a better solution to eliminate copying classes between two libs.** 

https://github.com/xmlking/micro-apps/tree/develop/libs/kstream

**Comment by thake** [comment]
@xmlking First of all thanks for your feedback :) It is always welcome! You should have no need to add the schema to the registry before using the serializer. The serializer should do this. I will add a new IT test to check the compatibility with the latest confluent Kafka Stream. This will be fixed before the next version is released.

Have you had a look at  https://github.com/QuickSign/kafka-encryption for adding an encryption/decryption layer to an existing Serde implementation? It should be possible to use it with avro4k without copying classes.

**Comment by xmlking** [comment]
Thank you for sharing **kafka-encryption**. I will research how to leverage it. 
for encryption , I wrapped Google’s tink library and taking advantage of tools provided for key rotation and data lifecycle management https://github.com/xmlking/micro-apps/tree/develop/libs/crypto

when you refactor, please expose hooks where we can easily extend your SerDe. I was hoping the api should work like Unix pipes.   `Object | avro4k transformer |  crypto transformer => bytes` vice versa

As my record level encryption is working, I am thinking to implement field level encryption with annotations. Something like this:
```kotlin
@Serializable
@ExperimentalSerializationApi
data class MyModel(
    @AvroProp("sensitive", "true") var name: String? = null,
    var city: String? = null,
    var state: String? = null
)
```
My plan is: 
Serialization :  object -> GenericRecord(GR) -> encrypt annotated fields via traversing schema and GR ->  Field level encrypted GenericRecord to bytes 
Will share when prototyping is ready.

**Comment by thake** [comment]
@xmlking field level encryption sounds like a reasonable feature. But I think it can easier be implemented using a custom serializer for avro4k as it directly affects the avro schema. Otherwise, you would end up having two avro schemas, one produced by the Kafka Serializer and the other one directly produced by avro4k. Have a look at https://github.com/avro-kotlin/avro4k-arrow/blob/master/src/main/kotlin/com/sksamuel/avro4k/arrow/Tuple2Serializer.kt for an example of a custom serializer.
