### ISSUE TITLE
Document which kafka-stream versions to use to avoid NoSuchMethodError

### ISSUE THREAD

**Issue by danieleascione** [thake/avro4k-kafka-serializer#17]
## The problem

While using the following versions

```groovy
dependencies {
    implementation(
        "com.github.thake.avro4k:avro4k-kafka-serializer:0.14.0" ,
        "org.apache.kafka:kafka-streams:3.2.3"
    )
}
```

in a Kafka Stream application, I had a failure in deserialization with the following stacktrace:

```
java.lang.NoSuchMethodError: 'byte[] org.apache.kafka.common.protocol.Readable.readArray(int)'
	at org.apache.kafka.streams.internals.generated.SubscriptionInfoData.read(SubscriptionInfoData.java:245)
	at org.apache.kafka.streams.internals.generated.SubscriptionInfoData.<init>(SubscriptionInfoData.java:163)
	at org.apache.kafka.streams.processor.internals.assignment.SubscriptionInfo.decode(SubscriptionInfo.java:352)
	at org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor.assign(StreamsPartitionAssignor.java:329)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onLeaderElected(ConsumerCoordinator.java:682)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.onLeaderElected(AbstractCoordinator.java:708)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.access$1000(AbstractCoordinator.java:112)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$JoinGroupResponseHandler.handle(AbstractCoordinator.java:612)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$JoinGroupResponseHandler.handle(AbstractCoordinator.java:575)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:1243)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:1218)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:602)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:412)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:297)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1306)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1242)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1215)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:969)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollPhase(StreamThread.java:917)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:736)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:589)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:551)
```

## Workaround

Downgrade kafka-stream to version`3.2.0`.

I am happy to give more context on how to replicate the issue if needed

## Suggested Solution

Create a compatibility matrix in the readme to make users aware of the Kafka version to use, as it's not currently clear (at least it was not clear to me).

**Comment by thake** [comment]
@danieleascione, thanks for raising this issue! Why do you think that my library is the culprit that is not compatible with kafka 3.2.3? The provided stack trace does point in a different direction.

**Comment by thake** [comment]
You were propably using kafka streams 3.2.3 together with a not-matching kafka-clients library. This might be because of autonomous transitive conflict resolution of your build tool favors version 7.2.1-ccs over version 3.2.3 of kafka-clients. You'll have to force version 3.2.3 of kafka-clients to make it work.

**Comment by danieleascione** [comment]
Hi @thake, thanks for the quick reply! Ok, that makes sense. I thought the culprit was avro4k-kafka-serializer, because if I used the Avro Serdes instead(and removing the dependency to avro4k-kafka-serializer) everything would be working fine. Allow me to experiment a little bit and see if I can replicate the issue in a puppy project. I'll close this for now.
